# Generated by Django 5.2.5 on 2025-08-20 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('EMPTY', 'EMPTY'), ('RENTED', 'RENTED'), ('MAINT', 'MAINT')], default='EMPTY', max_length=10)),
                ('bedrooms', models.PositiveIntegerField(default=1, help_text='Số phòng ngủ')),
                ('bathrooms', models.PositiveIntegerField(default=1, help_text='Số phòng tắm')),
                ('address', models.CharField(blank=True, default='', help_text='Địa chỉ phòng', max_length=255)),
                ('detail', models.TextField(blank=True, default='', help_text='Mô tả chi tiết về phòng')),
                ('image', models.ImageField(blank=True, help_text='Hình ảnh phòng', null=True, upload_to='rooms/')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('billing_cycle', models.CharField(default='MONTHLY', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ENDED', 'ENDED'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('elec_prev', models.IntegerField()),
                ('elec_curr', models.IntegerField()),
                ('water_prev', models.IntegerField()),
                ('water_curr', models.IntegerField()),
                ('elec_price', models.DecimalField(decimal_places=2, default=3500, max_digits=12)),
                ('water_price', models.DecimalField(decimal_places=2, default=7000, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.contract')),
            ],
            options={
                'unique_together': {('contract', 'period')},
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('room',), name='uniq_active_contract_per_room'),
        ),
    ]
