# Generated by Django 5.2.5 on 2025-08-22 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_datetime_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Người liên hệ khẩn cấp'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='CCCD/CMND'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Kỳ thanh toán (YYYY-MM)', max_length=7)),
                ('room_price', models.DecimalField(decimal_places=2, help_text='Tiền phòng', max_digits=12)),
                ('elec_cost', models.DecimalField(decimal_places=2, default=0, help_text='Tiền điện', max_digits=12)),
                ('water_cost', models.DecimalField(decimal_places=2, default=0, help_text='Tiền nước', max_digits=12)),
                ('service_cost', models.DecimalField(decimal_places=2, default=0, help_text='Phí dịch vụ', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Tổng tiền', max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE')], default='UNPAID', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày phát hành')),
                ('due_date', models.DateField(help_text='Ngày đến hạn thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.contract')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('contract', 'period')},
            },
        ),
    ]
