# Generated by Django 5.2.5 on 2025-08-13 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('elec_prev', models.IntegerField()),
                ('elec_curr', models.IntegerField()),
                ('water_prev', models.IntegerField()),
                ('water_curr', models.IntegerField()),
                ('elec_price', models.DecimalField(decimal_places=2, default=3500, max_digits=12)),
                ('water_price', models.DecimalField(decimal_places=2, default=7000, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.contract')),
            ],
            options={
                'unique_together': {('contract', 'period')},
            },
        ),
    ]
