# Generated by Django 5.2.5 on 2025-08-22 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_address_tenant_emergency_contact_tenant_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='SĐT người liên hệ khẩn cấp'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mối quan hệ với người liên hệ'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nghề nghiệp'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nơi làm việc'),
        ),
    ]
