# Generated by Django 5.2.5 on 2025-08-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_created_at_tenant_emergency_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách tất cả hình ảnh của phòng (base64)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Hình ảnh chính của phòng', null=True, upload_to='rooms/'),
        ),
    ]
