# Generated by Django 5.2.5 on 2025-08-22 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_created_at_tenant_emergency_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('BANK', 'Chuyển khoản'), ('ONLINE', 'Online')], default='BANK', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('FAILED', 'Thất bại')], default='CONFIRMED', max_length=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
