# Generated by Django 5.2.5 on 2025-08-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment'),
        ('core', '0005_room_images_alter_room_image'),
    ]

    operations = [
    ]
