# Generated by Django 5.2.5 on 2025-08-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0005_payment_0005_room_images_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='owner_email',
            field=models.EmailField(blank=True, default='', help_text='Email liên hệ chủ nhà', max_length=254),
        ),
        migrations.AddField(
            model_name='room',
            name='owner_name',
            field=models.CharField(blank=True, default='', help_text='Tên chủ nhà', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='owner_phone',
            field=models.CharField(blank=True, default='', help_text='Số điện thoại chủ nhà', max_length=20),
        ),
    ]
