# Generated by Django 5.2.5 on 2025-08-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contract_status_add_fk_rental_request'),
        ('core', '0010_alter_contract_status_add_rental_request_id'),
        ('core', '0010_create_rental_request_model'),
    ]

    operations = [
    ]
