# Generated by Django 5.2.5 on 2025-08-23 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20250823_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_image',
            field=models.ImageField(blank=True, help_text='Ảnh hợp đồng đã ký (nếu có)', null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiền thuê hàng tháng', max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 8, 23), help_text='Ngày kết thúc hợp đồng'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Ghi chú về hợp đồng'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 8, 23), help_text='Ngày bắt đầu hợp đồng'),
            preserve_default=False,
        ),
    ]
