# Generated by Django 5.2.5 on 2025-08-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contract_contract_image_contract_monthly_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_image_base64',
            field=models.TextField(blank=True, default='', help_text='Ảnh hợp đồng dạng base64'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.TextField(blank=True, help_text='Hình ảnh chính của phòng (base64 hoặc URL)', null=True),
        ),
    ]
