# Generated by Django 5.2.5 on 2025-08-24 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_datetime_and_image_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(limit_choices_to={'role': 'TENANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_image',
            field=models.ImageField(blank=True, help_text='Ảnh hợp đồng đã ký (nếu có)', null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_image_base64',
            field=models.TextField(blank=True, default='', help_text='Ảnh hợp đồng dạng base64'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Thời điểm tạo hợp đồng'),
        ),
        migrations.AddField(
            model_name='contract',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiền thuê hàng tháng', max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Ghi chú về hợp đồng'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách tất cả hình ảnh của phòng (base64)'),
        ),
        migrations.AddField(
            model_name='room',
            name='owner_email',
            field=models.EmailField(blank=True, default='', help_text='Email liên hệ chủ nhà', max_length=254),
        ),
        migrations.AddField(
            model_name='room',
            name='owner_name',
            field=models.CharField(blank=True, default='', help_text='Tên chủ nhà', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='owner_phone',
            field=models.CharField(blank=True, default='', help_text='Số điện thoại chủ nhà', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Ngày kết thúc hợp đồng'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(help_text='Ngày bắt đầu hợp đồng'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.TextField(blank=True, help_text='Hình ảnh chính của phòng (base64 hoặc URL)', null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Kỳ thanh toán (YYYY-MM)', max_length=7)),
                ('room_price', models.DecimalField(decimal_places=2, help_text='Tiền phòng', max_digits=12)),
                ('elec_cost', models.DecimalField(decimal_places=2, default=0, help_text='Tiền điện', max_digits=12)),
                ('water_cost', models.DecimalField(decimal_places=2, default=0, help_text='Tiền nước', max_digits=12)),
                ('service_cost', models.DecimalField(decimal_places=2, default=0, help_text='Phí dịch vụ', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Tổng tiền', max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE')], default='UNPAID', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày phát hành')),
                ('due_date', models.DateField(help_text='Ngày đến hạn thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.contract')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('contract', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('BANK', 'Chuyển khoản'), ('ONLINE', 'Online')], default='BANK', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('FAILED', 'Thất bại')], default='CONFIRMED', max_length=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', help_text='Lời nhắn từ tenant khi gửi yêu cầu xem nhà')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm gửi yêu cầu')),
                ('viewing_time', models.DateTimeField(help_text='Thời gian đề xuất xem nhà')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_requests', to='core.room')),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'TENANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='rental_request',
            field=models.OneToOneField(blank=True, help_text='Yêu cầu xem nhà dẫn đến hợp đồng này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_contract', to='core.rentalrequest'),
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
