# Generated by Django 5.2.5 on 2025-08-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Người liên hệ khẩn cấp'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='SĐT người liên hệ khẩn cấp'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mối quan hệ với người liên hệ'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='CCCD/CMND'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nghề nghiệp'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nơi làm việc'),
        ),
    ]
